### ISSUE TITLE
Remove cell IDs from notebooks

### ISSUE THREAD

**Issue by redeboer** [ComPWA/gluex-nstar#49]
Notebooks currently contain cell IDs, which is annoying in diffs

https://github.com/ComPWA/gluex-nstar/blob/d47db442d549cf5c142dd9a7aaf3519d5afef00d/docs/pgamma-state.ipynb#L451

They can be removed by `nbformat_minor` to `4`.

https://github.com/ComPWA/gluex-nstar/blob/d47db442d549cf5c142dd9a7aaf3519d5afef00d/docs/pgamma-state.ipynb#L775

There is a pre-commit hook for this in [ComPWA/policy](https://github.com/ComPWA/policy):

```yaml
repos:
  - repo: https://github.com/ComPWA/policy
    rev: 0.3.10
    hooks:
      - id: fix-nbformat-version
```
