### ISSUE TITLE
Clean up GitHub caches after closing PRs

### ISSUE THREAD

**Issue by redeboer** [ComPWA/gluex-nstar#66]
The Pixi caches stored for the GitHub workflows are quite large, see [here](https://github.com/ComPWA/gluex-nstar/actions/caches). It would be better to automatically remove the caches for the PRs once they are closed. You can do so with [this workflow](https://github.com/ComPWA/ampform/blob/ee3e01cb3796da1fd2d34855c5b9b291cac0843d/.github/workflows/clean-caches.yml):

```yaml
name: Clean caches

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
    inputs:
      ref:
        description: Clean caches for this branch name or ref
        required: false
        type: string

jobs:
  cleanup:
    name: Remove caches
    runs-on: ubuntu-22.04
    steps:
      - uses: ComPWA/actions/clean-caches@v1
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ inputs.ref }}
```

[![image](https://github.com/user-attachments/assets/033a6f3b-1098-497f-b7f5-2a11a8d1534f)](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy)
